// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxtlofnzcqdpzjkohpsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4dGxvZm56Y3FkcHpqa29ocHNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMzI2MjMsImV4cCI6MjA3MjYwODYyM30.KN3v3iUEIamuchZcr_OyNY-WVnJBLOUQVzsw78DMQCI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});